print()
print("===== Personal Information =====")
print("Name:", name)
print("City:", city)
print("Current Age:", age)
print("Next Year Age:", age + 1)
print("Age in Five Years:", age + 5)
print("Dream Monthly Salary:", dream_salary)
print("Monthly Salary After 10% Increase:", dream_salary * 1.1)
print("Dream Yearly Salary:", dream_salary * 12)
